(ns quo2.core-spec
  (:require [quo2.components.avatars.user-avatar.component-spec]
            [quo2.components.banners.banner.component-spec]
            [quo2.components.buttons.button-component-spec]
            [quo2.components.counter.component-spec]
            [quo2.components.dividers.divider-label-component-spec]
            [quo2.components.dividers.strength-divider.component-spec]
            [quo2.components.drawers.action-drawers.component-spec]
            [quo2.components.drawers.drawer-buttons.component-spec]
            [quo2.components.drawers.permission-context.component-spec]
            [quo2.components.colors.color-picker.component-spec]
            [quo2.components.inputs.profile-input.component-spec]
            [quo2.components.inputs.title-input.component-spec]
            [quo2.components.markdown.text-component-spec]
            [quo2.components.onboarding.small-option-card.component-spec]
            [quo2.components.password.tips.component-spec]
            [quo2.components.record-audio.record-audio.component-spec]
            [quo2.components.record-audio.soundtrack.component-spec]
            [quo2.components.profile.select-profile.component-spec]
            [quo2.components.selectors.selectors-component-spec]
            [quo2.components.selectors.filter.component-spec]
            [quo2.components.tags.status-tags-component-spec]))
